# Generated by Django 3.2.7 on 2021-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
