# Generated by Django 3.2.6 on 2021-09-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
