# Generated by Django 3.2.6 on 2021-10-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210924_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='firstname',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeruser',
            name='lastname',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
